projectName: wqp-external
dockerImageName: kartoza/geoserver
memory: 4096
applicationName: wqp-geoserver
rulePriority: 93
containerPort: 8080
healthCheck: /geoserver/web/
condition: /geoserver/*
gitRepoUrl: https://github.com/NWQMC/wqp-geoserver.git
gitRepoCredentialsId: GITHUB_ACCESS_TOKEN
healthCheckTimeoutSeconds: 45
healthCheckIntervalSeconds: 60
listenerPort: 443
envVars:
  - name: GEOSERVER_DATA_DIR
    value: /data
mounts:
  - name: GEOSERVER_DATA_DIR_MOUNT
    source: /efs
    destination: /data
    readOnly: False
