projectName: wqp-external
dockerImageName: kartoza/geoserver
memory: 3072
cpu: 1024
applicationName: wqp-geoserver
containerPort: 8080
healthCheck: /geoserver/web/
gitRepoUrl: https://github.com/NWQMC/wqp-geoserver.git
gitRepoCredentialsId: GITHUB_ACCESS_TOKEN
healthCheckTimeoutSeconds: 45
healthCheckIntervalSeconds: 60
listenerPort: 443
# configuration repository paths
configRepoPath: "wma/docker/wqp/wqp-geoserver"
configCredentialsId: "wma-eto-eb-rsa"
urlRules:
  - type: forward
    conditions:
      - "/geoserver/*"
    priority: 93
tags:
  wma:costCenter: TBD
  wma:organization: iow
  wma:contact: TBD
  wma:taggingVersion: 0.0.1
  wma:project_id: wqp
